# @file ~/.config/mise/config.toml
# ref:
# https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml

[tools]
# global tool versions go here
python = '3.10'     # https://github.com/jdx/mise/blob/main/docs/python.md
uv = "latest"

java = 'openjdk-17' # https://github.com/jdx/mise/blob/main/docs/java.md

node = 'lts'     # https://github.com/jdx/mise/blob/main/docs/node.md
"npm:pnpm" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
